### ISSUE TITLE
1-month cloud benchmark plots jobs failing 

### ISSUE THREAD

**Issue by yantosca** [geoschem/gc-cloud-infrastructure#36]
Hi @laestrada: We are running into the situation where the 1-month cloud benchmarks are failing, presumably due to lack of memory.  I was wondering if we can bump up the memory for these jobs, and maybe also try using less cores, since less cores means less stack memory used (and potentially leaked).

Also tagging @msulprizio @lizziel

**Comment by yantosca** [comment]
Update:
- [GCC 14.1.1 vs 14.1.0 comparison finished OK](http://s3.amazonaws.com/benchmarks-cloud/diff-plots/1Mon/diff-gcc-4x5-1Mon-14.1.0-gcc-4x5-1Mon-14.1.1/BenchmarkResults/Tables/Summary.txt)
- [GCHP 14.1.1 vs. 14.1.0 comparison finished OK](http://s3.amazonaws.com/benchmarks-cloud/diff-plots/1Mon/diff-gchp-c24-1Mon-14.1.0-gchp-c24-1Mon-14.1.1/BenchmarkResults/GCHP_version_comparison/Tables/Summary.txt)
- GCHP 14.1.1 vs. GCC 14.1.1 failed
- Diff-of-diffs 14.1.1 failed

Error output shows a memory issue:
Log: http://s3.amazonaws.com/benchmarks-cloud/diff-plots/1Mon/diff-of-diffs-1Mon-gchp-c24-gcc-4x5-14.1.0-14.1.1/CreateBenchmarkPlots.txt
```console
Using configuration file /tmp/tmp.oQr92SGAbr/gcpy/gcpy/benchmark_categories.yml

Archiving benchmark_categories.yml in /tmp/tmp.oQr92SGAbr/dev-gchp/run-directory/BenchmarkResults/GCHP_GCC_diff_of_diffs
Traceback (most recent call last):
  File "/tmp/tmp.oQr92SGAbr/gcpy/benchmark/run_benchmark.py", line 1515, in <module>
    main()
  File "/tmp/tmp.oQr92SGAbr/gcpy/benchmark/run_benchmark.py", line 1511, in main
    choose_benchmark_type(config)
  File "/tmp/tmp.oQr92SGAbr/gcpy/benchmark/run_benchmark.py", line 109, in choose_benchmark_type
    run_benchmark_default(config)
  File "/tmp/tmp.oQr92SGAbr/gcpy/benchmark/run_benchmark.py", line 1482, in run_benchmark_default
    bmk.make_benchmark_conc_plots(
  File "/tmp/tmp.oQr92SGAbr/gcpy/gcpy/benchmark.py", line 1227, in make_benchmark_conc_plots
    results = Parallel(n_jobs=n_job)(
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/conda/envs/py39/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/opt/conda/envs/py39/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
```

**Comment by laestrada** [comment]
I bumped the container to 150GB. I wonder if the gcpy benchmark plots should have an option to run without parallelism? Both to reduce the memory load and also to help debug issues -- as often errors get masked behind the joblib parallel command.

**Comment by yantosca** [comment]
@laestrada, we can try to add a switch for parallelization to GCPy.  The only thing is that without parallelization it can take about 2.5 hours for the GCHP plots.  The other thing we can try is using less cores.
